name: MediaBans
version: '1.0'
main: ru.dscraft.mediabans.MediaBansPlugin
api-version: '1.21'
author: loserwrld
description: Баны, муты и кики Amaterasu
# грузимся после них и забираем себе /ban, /mute, /kick ...
softdepend: [LuckPerms, Essentials, LiteBans, AdvancedBan, BanManager, CMI]
commands:
  ban:
    description: Забанить навсегда (команда проекта)
    usage: /ban <ник> [причина]
  tempban:
    description: Забанить на время
    usage: /tempban <ник> <время> [причина]
    aliases: [tban]
  mute:
    description: Замутить навсегда (команда проекта)
    usage: /mute <ник> [причина]
  tempmute:
    description: Замутить на время
    usage: /tempmute <ник> <время> [причина]
    aliases: [tmute]
  kick:
    description: Кикнуть игрока (команда проекта)
    usage: /kick <ник> [причина]
  unban:
    description: Разбанить
    usage: /unban <ник>
    aliases: [pardon]
  unmute:
    description: Снять мут
    usage: /unmute <ник>
  checkban:
    description: Информация о бане
    usage: /checkban <ник>
  checkmute:
    description: Информация о муте
    usage: /checkmute <ник>
  banlist:
    description: Список забаненных
    usage: /banlist [страница]
    aliases: [bans]
  mediabans:
    description: Перезагрузка конфига MediaBans
    usage: /mediabans reload
permissions:
  mediabans.staff:
    description: Наказывать без ограничений и не получать наказаний, как команда проекта
    default: false
